### ISSUE TITLE
Consider using `~/.babashka/bbin` directory

### ISSUE THREAD

**Issue by borkdude** [babashka/bbin#25]
We already store pods in `~/.babashka/pods`. I think it would make sense to use the `~/.babashka/bbin` directory. This saves creating another bb-related directory on the top level of a user directory.

Check the pods project how this directory is detected. It respects `XDG_` environment variables.

cc @rads @bobisageek

**Comment by rads** [comment]
Sounds good to me.

**Comment by rads** [comment]
Forgot to add the XDG stuff before closing this, I'll add this next.
