### ISSUE TITLE
Support `XDG_DATA_HOME` env variable

### ISSUE THREAD

**Issue by rads** [babashka/bbin#26]
Follow up from https://github.com/babashka/bbin/issues/25.

**Comment by ieugen** [comment]
I thnk this should re re-opened:

> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
