### ISSUE TITLE
bbin install [LOCAL-FILE] should not be restricted to files with the .clj extension

### ISSUE THREAD

**Issue by mtwomey** [babashka/bbin#72]
It would be preferable if you could install local scripts _not_ ending in `.clj` using `bbin install`. 

For example, I personally prefer to name my babashka scripts with the `.bb` extension to differentiate them.

**Comment by rads** [comment]
Thanks for the bug report. I can go ahead and add the `.bb` extension no problem.

As for installing _any_ file extension, I need to think about this some more given that we're using the file extension for other use cases, such as `.jar` files.

**Comment by borkdude** [comment]
To me it makes sense to treat any extension as a bb script, _unless_ it's a specific extension like `.jar`

**Comment by borkdude** [comment]
It seems `.cljc` isn't treated as a script either.

**Comment by mtwomey** [comment]
@rads Thank you, this does solve my issue. I do wonder if @borkdude 's thought about "reversing" the logic so that is treats files as bb scripts by default (with specific exceptions) might have more utility in the long run?

**Comment by rads** [comment]
Makes sense. I reopened this issue and will follow up with some more changes later.

**Comment by borkdude** [comment]
Since @rads doesn't maintain this tool anymore (or soon-ish) and this issue hit some other person as well recently, I'll have a look at this issue soon-ish, hopefully.

**Comment by rads** [comment]
This is now fixed in 0.2.3 (any extension can be used).

**Comment by borkdude** [comment]
Thanks a lot @rads !
